import { db } from "./db";
import { listings, users } from "@shared/schema";
import { sql } from "drizzle-orm";

const demoUsers = [
  { id: "demo-user-001", phone: "+905301110001", name: "Ahmet Yılmaz", city: "İstanbul", trustScore: 92, userType: "bireysel" },
  { id: "demo-user-002", phone: "+905301110002", name: "Mehmet Kaya", city: "Ankara", trustScore: 88, userType: "bireysel" },
  { id: "demo-user-003", phone: "+905301110003", name: "Emre Demir", city: "İzmir", trustScore: 95, userType: "bireysel" },
  { id: "demo-user-004", phone: "+905301110004", name: "Burak Çelik", city: "Bursa", trustScore: 80, userType: "bireysel" },
  { id: "demo-user-005", phone: "+905301110005", name: "Can Öztürk", city: "Antalya", trustScore: 85, userType: "bireysel" },
  { id: "demo-user-006", phone: "+905301110006", name: "Serkan Aydın", city: "İstanbul", trustScore: 90, userType: "kurumsal" },
  { id: "demo-user-007", phone: "+905301110007", name: "Oğuz Şahin", city: "Konya", trustScore: 78, userType: "bireysel" },
  { id: "demo-user-008", phone: "+905301110008", name: "Tolga Arslan", city: "Adana", trustScore: 82, userType: "bireysel" },
];

const DEMO_NOTE = "\n\n--- Bu ilan demo amaclidir. Gercek bir ilan degildir. ---";

const demoListings = [
  { id: "demo-listing-001", userId: "demo-user-001", brand: "BMW", model: "320i M Sport", year: 2021, km: 42000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Kadıköy", estimatedValue: 2150000, description: "Temiz kullanılmış, kazasız, boyasız araç. M Sport paket, Harman Kardon ses sistemi, panoramik cam tavan mevcut. Tüm bakımları yetkili serviste yapılmıştır. Kış ve yaz lastik takımı mevcuttur." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=600&h=400&fit=crop"], preferredBrands: ["Mercedes", "Audi"], swapActive: true, isFeatured: true, status: "active", viewCount: 234, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-002", userId: "demo-user-002", brand: "Mercedes-Benz", model: "C200 AMG", year: 2020, km: 58000, fuelType: "Benzin", transmission: "Otomatik", city: "Ankara", district: "Çankaya", estimatedValue: 2350000, description: "AMG paket, gece paketi, Burmester ses sistemi. Tüm bakımları yetkili serviste yapılmıştır. Araç garaj aracıdır, sigara içilmemiştir." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Audi", "Volvo"], swapActive: true, isFeatured: true, status: "active", viewCount: 312, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-003", userId: "demo-user-003", brand: "Audi", model: "A4 45 TFSI Quattro", year: 2022, km: 18000, fuelType: "Benzin", transmission: "Otomatik", city: "İzmir", district: "Karşıyaka", estimatedValue: 2800000, description: "Quattro 4x4, Virtual Cockpit, Matrix LED farlar. Garantisi devam etmektedir. Araç kusursuz durumda olup ilk sahibinden satılıktır." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Mercedes"], swapActive: true, isFeatured: true, status: "active", viewCount: 198, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-004", userId: "demo-user-004", brand: "Volkswagen", model: "Golf 8 R-Line", year: 2021, km: 35000, fuelType: "Benzin", transmission: "Otomatik", city: "Bursa", district: "Nilüfer", estimatedValue: 1650000, description: "R-Line paket, dijital kokpit, LED farlar, 18 inç jantlar. Araç hatasız olup tüm bakımları düzenli yapılmıştır." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Audi", "Ford"], swapActive: true, isFeatured: true, status: "active", viewCount: 267, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-005", userId: "demo-user-005", brand: "Toyota", model: "Corolla 1.8 Hybrid", year: 2023, km: 12000, fuelType: "Hibrit", transmission: "Otomatik", city: "Antalya", district: "Muratpaşa", estimatedValue: 1480000, description: "Sıfır ayarında hibrit araç. 4.2L/100km yakıt tüketimi. Toyota Safety Sense güvenlik paketi, adaptif cruise control mevcut." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&h=400&fit=crop"], preferredBrands: ["Honda", "Mazda", "Hyundai"], swapActive: true, isFeatured: false, status: "active", viewCount: 156, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-006", userId: "demo-user-006", brand: "Volvo", model: "XC60 T5 Inscription", year: 2020, km: 65000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Sarıyer", estimatedValue: 2900000, description: "Inscription paket, Pilot Assist, Bowers & Wilkins ses sistemi, 360 derece kamera. İskandinav güvenliği ve lüksü bir arada." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Mercedes", "Audi"], swapActive: true, isFeatured: true, status: "active", viewCount: 189, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-007", userId: "demo-user-001", brand: "Honda", model: "Civic 1.5 VTEC RS", year: 2022, km: 20000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Beşiktaş", estimatedValue: 1750000, description: "RS paket, 1.5 VTEC Turbo 182 HP, Honda Sensing güvenlik paketi, sportif ve güvenilir. İlk sahibinden." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1679420437432-d9c105fbbff0?w=600&h=400&fit=crop"], preferredBrands: ["Toyota", "Mazda"], swapActive: true, isFeatured: false, status: "active", viewCount: 178, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-008", userId: "demo-user-007", brand: "Ford", model: "Kuga 1.5 EcoBoost ST-Line", year: 2021, km: 40000, fuelType: "Benzin", transmission: "Otomatik", city: "Konya", district: "Selçuklu", estimatedValue: 1550000, description: "ST-Line paket, panoramik cam tavan, elektrikli bagaj kapağı, B&O ses sistemi. Geniş iç hacim ve sportif tasarım." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1551830820-330a71b99659?w=600&h=400&fit=crop"], preferredBrands: ["Volkswagen", "Peugeot", "Hyundai"], swapActive: true, isFeatured: false, status: "active", viewCount: 134, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-009", userId: "demo-user-002", brand: "Hyundai", model: "Tucson 1.6 CRDI Elite", year: 2022, km: 25000, fuelType: "Dizel", transmission: "Otomatik", city: "Ankara", district: "Yenimahalle", estimatedValue: 1680000, description: "Elite paket, akıllı park asistanı, şerit takip sistemi, kablosuz şarj. Ekonomik dizel motor ile uzun yol konforu." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1626668011687-8a114cf5a34c?w=600&h=400&fit=crop"], preferredBrands: ["Kia", "Toyota", "Nissan"], swapActive: true, isFeatured: false, status: "active", viewCount: 201, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-010", userId: "demo-user-003", brand: "Mazda", model: "CX-5 2.0 SKY-G Power", year: 2021, km: 30000, fuelType: "Benzin", transmission: "Otomatik", city: "İzmir", district: "Bornova", estimatedValue: 1720000, description: "Power paket, BOSE ses sistemi, deri döşeme, G-Vectoring Control. Sürüş keyfi arayanlar için ideal SUV." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&h=400&fit=crop"], preferredBrands: ["Toyota", "Honda", "Subaru"], swapActive: true, isFeatured: true, status: "active", viewCount: 145, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-011", userId: "demo-user-008", brand: "Renault", model: "Megane 1.3 TCe Icon", year: 2021, km: 45000, fuelType: "Benzin", transmission: "Otomatik", city: "Adana", district: "Seyhan", estimatedValue: 980000, description: "Icon donanım, 9.3 inç multimedya ekranı, geri görüş kamerası, otomatik klima. Ekonomik ve konforlu sedan." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1549317661-bd32c8ce0afe?w=600&h=400&fit=crop"], preferredBrands: ["Peugeot", "Citroen", "Fiat"], swapActive: true, isFeatured: false, status: "active", viewCount: 112, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-012", userId: "demo-user-005", brand: "Peugeot", model: "3008 1.5 BlueHDi GT", year: 2020, km: 55000, fuelType: "Dizel", transmission: "Otomatik", city: "Antalya", district: "Kepez", estimatedValue: 1450000, description: "GT paket, i-Cockpit dijital gösterge paneli, gece görüş sistemi, Focal ses sistemi. Premium SUV deneyimi." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&h=400&fit=crop"], preferredBrands: ["Renault", "Citroen", "Volkswagen"], swapActive: true, isFeatured: false, status: "active", viewCount: 167, accidentFree: false, tramerRecord: 12500 },
  { id: "demo-listing-013", userId: "demo-user-006", brand: "BMW", model: "X3 xDrive20i M Sport", year: 2022, km: 22000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Ataşehir", estimatedValue: 3200000, description: "M Sport paket, xDrive 4x4, head-up display, harman kardon, panoramik tavan. Premium SUV segment lideri." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1556189250-72ba954cfc2b?w=600&h=400&fit=crop"], preferredBrands: ["Mercedes", "Audi", "Volvo"], swapActive: true, isFeatured: true, status: "active", viewCount: 289, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-014", userId: "demo-user-004", brand: "Kia", model: "Sportage 1.6 T-GDI GT-Line", year: 2023, km: 8000, fuelType: "Benzin", transmission: "Otomatik", city: "Bursa", district: "Osmangazi", estimatedValue: 1850000, description: "GT-Line paket, panoramik çift ekran, Harman Kardon, ventilasyonlu koltuklar. Yılın otomobili ödüllü SUV." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=600&h=400&fit=crop"], preferredBrands: ["Hyundai", "Toyota", "Honda"], swapActive: true, isFeatured: true, status: "active", viewCount: 321, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-015", userId: "demo-user-007", brand: "Skoda", model: "Octavia 1.5 TSI Style", year: 2022, km: 28000, fuelType: "Benzin", transmission: "Otomatik", city: "Konya", district: "Meram", estimatedValue: 1320000, description: "Style paket, canton ses sistemi, 10 inç infotainment, adaptive cruise control. Sınıfının en geniş iç hacmi." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&h=400&fit=crop"], preferredBrands: ["Volkswagen", "Seat", "Toyota"], swapActive: true, isFeatured: false, status: "active", viewCount: 98, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-016", userId: "demo-user-001", brand: "Mercedes-Benz", model: "GLA 200 AMG", year: 2021, km: 35000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Bakırköy", estimatedValue: 2450000, description: "AMG Line paket, MBUX multimedya, ambiyans aydınlatma, 360 derece kamera. Kompakt premium SUV." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Audi"], swapActive: true, isFeatured: true, status: "active", viewCount: 245, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-017", userId: "demo-user-008", brand: "Fiat", model: "Egea 1.4 Urban Plus", year: 2022, km: 32000, fuelType: "Benzin", transmission: "Manuel", city: "Adana", district: "Çukurova", estimatedValue: 720000, description: "Urban Plus donanım, 7 inç multimedya, geri görüş kamerası, cruise control. Ekonomik ve pratik sedan." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&h=400&fit=crop"], preferredBrands: ["Renault", "Peugeot", "Citroen"], swapActive: true, isFeatured: false, status: "active", viewCount: 87, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-018", userId: "demo-user-002", brand: "Audi", model: "Q3 35 TFSI S-Line", year: 2021, km: 40000, fuelType: "Benzin", transmission: "Otomatik", city: "Ankara", district: "Etimesgut", estimatedValue: 2200000, description: "S-Line paket, virtual cockpit plus, MMI navigasyon, LED matrix farlar. Sportif kompakt SUV." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1542362567-b07e54358753?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Mercedes", "Volvo"], swapActive: true, isFeatured: false, status: "active", viewCount: 176, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-019", userId: "demo-user-003", brand: "Nissan", model: "Qashqai 1.3 DIG-T Tekna", year: 2022, km: 20000, fuelType: "Benzin", transmission: "Otomatik", city: "İzmir", district: "Bayraklı", estimatedValue: 1520000, description: "Tekna paket, ProPilot otonom sürüş, 360 kamera, massajlı koltuk. Crossover segmentinin öncüsü." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1533473359331-2f2db3c5d4c6?w=600&h=400&fit=crop"], preferredBrands: ["Toyota", "Honda", "Hyundai"], swapActive: true, isFeatured: false, status: "active", viewCount: 143, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-020", userId: "demo-user-005", brand: "Seat", model: "Leon 1.5 TSI FR", year: 2021, km: 38000, fuelType: "Benzin", transmission: "Otomatik", city: "Antalya", district: "Konyaaltı", estimatedValue: 1180000, description: "FR paket, dijital kokpit, beats ses sistemi, full LED farlar. İspanyol sportifliği ve Alman mühendisliği." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&h=400&fit=crop"], preferredBrands: ["Volkswagen", "Skoda", "Ford"], swapActive: true, isFeatured: false, status: "active", viewCount: 121, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-021", userId: "demo-user-006", brand: "BMW", model: "520i M Sport", year: 2020, km: 68000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Üsküdar", estimatedValue: 2750000, description: "M Sport paket, Comfort Access, Driving Assistant Plus, gesture control. Executive sedan segmentinin yıldızı." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&h=400&fit=crop"], preferredBrands: ["Mercedes", "Audi"], swapActive: true, isFeatured: true, status: "active", viewCount: 356, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-022", userId: "demo-user-004", brand: "Citroen", model: "C5 Aircross 1.5 BlueHDi Shine", year: 2021, km: 42000, fuelType: "Dizel", transmission: "Otomatik", city: "Bursa", district: "Yıldırım", estimatedValue: 1280000, description: "Shine paket, Advanced Comfort koltuklar, grip control, 12.3 inç dijital gösterge. Fransız konforu SUV'da." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&h=400&fit=crop"], preferredBrands: ["Peugeot", "Renault", "Opel"], swapActive: true, isFeatured: false, status: "active", viewCount: 109, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-023", userId: "demo-user-007", brand: "Toyota", model: "C-HR 1.8 Hybrid Passion", year: 2022, km: 15000, fuelType: "Hibrit", transmission: "Otomatik", city: "Konya", district: "Karatay", estimatedValue: 1580000, description: "Passion paket, JBL ses sistemi, head-up display, kablosuz şarj. Çarpıcı tasarım ve hibrit verimlilik." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600&h=400&fit=crop"], preferredBrands: ["Honda", "Mazda", "Hyundai"], swapActive: true, isFeatured: false, status: "active", viewCount: 187, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-024", userId: "demo-user-008", brand: "Opel", model: "Astra 1.2 Turbo GS Line", year: 2023, km: 10000, fuelType: "Benzin", transmission: "Otomatik", city: "Adana", district: "Sarıçam", estimatedValue: 1150000, description: "GS Line paket, Intelli-Lux matrix LED, pure panel dijital kokpit. Yeni nesil tasarım ve teknoloji." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&h=400&fit=crop"], preferredBrands: ["Peugeot", "Ford", "Volkswagen"], swapActive: true, isFeatured: false, status: "active", viewCount: 95, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-025", userId: "demo-user-001", brand: "Mercedes-Benz", model: "E200 Exclusive", year: 2019, km: 78000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Şişli", estimatedValue: 2600000, description: "Exclusive paket, widescreen cockpit, Burmester 3D surround, multibeam LED. Lüks ve prestijin adı." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Audi"], swapActive: true, isFeatured: true, status: "active", viewCount: 298, accidentFree: false, tramerRecord: 18000 },
  { id: "demo-listing-026", userId: "demo-user-003", brand: "Volkswagen", model: "Tiguan 1.5 TSI Elegance", year: 2022, km: 25000, fuelType: "Benzin", transmission: "Otomatik", city: "İzmir", district: "Çiğli", estimatedValue: 1780000, description: "Elegance paket, IQ.DRIVE asistan sistemleri, panoramik tavan, elektrikli bagaj. Ailenin güvenilir SUV'u." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=600&h=400&fit=crop"], preferredBrands: ["Skoda", "Seat", "Ford"], swapActive: true, isFeatured: false, status: "active", viewCount: 213, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-027", userId: "demo-user-002", brand: "Subaru", model: "XV 2.0i Premium", year: 2020, km: 50000, fuelType: "Benzin", transmission: "Otomatik", city: "Ankara", district: "Keçiören", estimatedValue: 1350000, description: "Symmetrical AWD, EyeSight güvenlik, X-Mode arazi modu, Starlink multimedya. Macera için tasarlandı." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&h=400&fit=crop"], preferredBrands: ["Toyota", "Honda", "Mazda"], swapActive: true, isFeatured: false, status: "active", viewCount: 88, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-028", userId: "demo-user-005", brand: "Dacia", model: "Duster 1.3 TCe Journey", year: 2023, km: 5000, fuelType: "Benzin", transmission: "Otomatik", city: "Antalya", district: "Lara", estimatedValue: 920000, description: "Journey paket, 8 inç multimedya, kablosuz Apple CarPlay, otomatik klima. Uygun fiyatlı SUV alternatifi." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&h=400&fit=crop"], preferredBrands: ["Renault", "Fiat", "Citroen"], swapActive: true, isFeatured: false, status: "active", viewCount: 76, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-029", userId: "demo-user-006", brand: "Audi", model: "A6 40 TFSI Design", year: 2021, km: 45000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Kartal", estimatedValue: 2950000, description: "Design paket, çift MMI dokunmatik ekran, virtual cockpit plus, Matrix LED farlar. İş dünyasının tercihi." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Mercedes", "Volvo"], swapActive: true, isFeatured: true, status: "active", viewCount: 267, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-030", userId: "demo-user-004", brand: "Cupra", model: "Formentor 1.5 TSI VZ", year: 2022, km: 22000, fuelType: "Benzin", transmission: "Otomatik", city: "Bursa", district: "Mudanya", estimatedValue: 1620000, description: "VZ paket, Brembo frenler, adaptif süspansiyon, Beats ses sistemi. Performans odaklı crossover." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1612825173281-9a193378527e?w=600&h=400&fit=crop"], preferredBrands: ["Volkswagen", "Seat", "BMW"], swapActive: true, isFeatured: false, status: "active", viewCount: 198, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-031", userId: "demo-user-007", brand: "Honda", model: "HR-V 1.5 e:HEV Advance", year: 2023, km: 8000, fuelType: "Hibrit", transmission: "Otomatik", city: "Konya", district: "Selçuklu", estimatedValue: 1480000, description: "Advance paket, e:HEV hibrit sistem, Honda CONNECT, wireless Apple CarPlay. Kompakt SUV'da hibrit teknolojisi." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&h=400&fit=crop"], preferredBrands: ["Toyota", "Mazda", "Hyundai"], swapActive: true, isFeatured: false, status: "active", viewCount: 132, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-032", userId: "demo-user-008", brand: "BMW", model: "118i M Sport", year: 2021, km: 30000, fuelType: "Benzin", transmission: "Otomatik", city: "Adana", district: "Yüreğir", estimatedValue: 1650000, description: "M Sport paket, live cockpit, BMW intelligent personal assistant, park asistanı. Kompakt premium." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1590362891991-f776e747a588?w=600&h=400&fit=crop"], preferredBrands: ["Mercedes", "Audi"], swapActive: true, isFeatured: false, status: "active", viewCount: 165, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-033", userId: "demo-user-001", brand: "Volvo", model: "S60 T5 R-Design", year: 2020, km: 52000, fuelType: "Benzin", transmission: "Otomatik", city: "İstanbul", district: "Maltepe", estimatedValue: 2100000, description: "R-Design paket, Pilot Assist, Harman Kardon, 360 kamera. İskandinav tasarımı sportif sedan." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1550355291-bbee04a92027?w=600&h=400&fit=crop"], preferredBrands: ["BMW", "Mercedes", "Audi"], swapActive: true, isFeatured: false, status: "active", viewCount: 142, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-034", userId: "demo-user-002", brand: "Ford", model: "Focus 1.5 EcoBoost ST-Line X", year: 2021, km: 36000, fuelType: "Benzin", transmission: "Otomatik", city: "Ankara", district: "Gölbaşı", estimatedValue: 1150000, description: "ST-Line X paket, 8 inç SYNC 3, B&O ses sistemi, adaptif cruise. Sürüş keyfi arayanlar için hatchback." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=600&h=400&fit=crop"], preferredBrands: ["Volkswagen", "Seat", "Peugeot"], swapActive: true, isFeatured: false, status: "active", viewCount: 108, accidentFree: true, tramerRecord: 0 },
  { id: "demo-listing-035", userId: "demo-user-003", brand: "Jeep", model: "Compass 1.3 T4 Limited", year: 2022, km: 18000, fuelType: "Benzin", transmission: "Otomatik", city: "İzmir", district: "Konak", estimatedValue: 1680000, description: "Limited paket, Uconnect 10.1 inç, Alpine ses sistemi, full LED. Amerikan ruhu İtalyan tasarımıyla buluşuyor." + DEMO_NOTE, photos: ["https://images.unsplash.com/photo-1519245659620-e859806a8d3b?w=600&h=400&fit=crop"], preferredBrands: ["Toyota", "Ford", "Hyundai"], swapActive: true, isFeatured: false, status: "active", viewCount: 156, accidentFree: true, tramerRecord: 0 },
];

export async function seedDemoData(): Promise<void> {
  try {
    const existingListings = await db.select({ count: sql<number>`count(*)` }).from(listings);
    const count = Number(existingListings[0]?.count || 0);
    
    if (count >= 30) {
      console.log(`Database already has ${count} listings, skipping seed.`);
      return;
    }

    console.log("Seeding demo data...");

    for (const user of demoUsers) {
      const existing = await db.select().from(users).where(sql`id = ${user.id}`);
      if (existing.length === 0) {
        await db.insert(users).values({
          ...user,
          phoneVerified: true,
          identityVerified: true,
        });
      }
    }
    console.log(`${demoUsers.length} demo users created.`);

    for (const listing of demoListings) {
      const existing = await db.select().from(listings).where(sql`id = ${listing.id}`);
      if (existing.length === 0) {
        await db.insert(listings).values(listing);
      }
    }

    console.log(`Seeded ${demoListings.length} demo listings.`);
  } catch (error) {
    console.error("Error seeding demo data:", error);
  }
}
