export interface VehicleModel {
  name: string;
  years?: string;
}

export interface VehicleBrand {
  name: string;
  models: VehicleModel[];
}

export const VEHICLE_BRANDS: VehicleBrand[] = [
  {
    name: "Audi",
    models: [
      { name: "A1" },
      { name: "A3" },
      { name: "A4" },
      { name: "A5" },
      { name: "A6" },
      { name: "A7" },
      { name: "A8" },
      { name: "Q2" },
      { name: "Q3" },
      { name: "Q5" },
      { name: "Q7" },
      { name: "Q8" },
      { name: "e-tron" },
      { name: "e-tron GT" },
      { name: "RS3" },
      { name: "RS4" },
      { name: "RS5" },
      { name: "RS6" },
      { name: "RS7" },
      { name: "S3" },
      { name: "S4" },
      { name: "S5" },
      { name: "TT" },
    ],
  },
  {
    name: "BMW",
    models: [
      { name: "1 Serisi" },
      { name: "2 Serisi" },
      { name: "3 Serisi" },
      { name: "4 Serisi" },
      { name: "5 Serisi" },
      { name: "6 Serisi" },
      { name: "7 Serisi" },
      { name: "8 Serisi" },
      { name: "X1" },
      { name: "X2" },
      { name: "X3" },
      { name: "X4" },
      { name: "X5" },
      { name: "X6" },
      { name: "X7" },
      { name: "Z4" },
      { name: "i3" },
      { name: "i4" },
      { name: "i7" },
      { name: "iX" },
      { name: "iX1" },
      { name: "iX3" },
      { name: "M2" },
      { name: "M3" },
      { name: "M4" },
      { name: "M5" },
      { name: "M8" },
    ],
  },
  {
    name: "Mercedes-Benz",
    models: [
      { name: "A Serisi" },
      { name: "B Serisi" },
      { name: "C Serisi" },
      { name: "CLA" },
      { name: "CLS" },
      { name: "E Serisi" },
      { name: "S Serisi" },
      { name: "GLA" },
      { name: "GLB" },
      { name: "GLC" },
      { name: "GLE" },
      { name: "GLS" },
      { name: "G Serisi" },
      { name: "EQA" },
      { name: "EQB" },
      { name: "EQC" },
      { name: "EQE" },
      { name: "EQS" },
      { name: "AMG GT" },
      { name: "Maybach" },
      { name: "Vito" },
      { name: "V Serisi" },
      { name: "Sprinter" },
    ],
  },
  {
    name: "Volkswagen",
    models: [
      { name: "Polo" },
      { name: "Golf" },
      { name: "Passat" },
      { name: "Arteon" },
      { name: "T-Cross" },
      { name: "T-Roc" },
      { name: "Tiguan" },
      { name: "Touareg" },
      { name: "ID.3" },
      { name: "ID.4" },
      { name: "ID.5" },
      { name: "ID.7" },
      { name: "Caddy" },
      { name: "Transporter" },
      { name: "Caravelle" },
      { name: "Multivan" },
      { name: "Amarok" },
      { name: "Jetta" },
      { name: "Scirocco" },
      { name: "Beetle" },
      { name: "CC" },
      { name: "Up" },
    ],
  },
  {
    name: "Toyota",
    models: [
      { name: "Yaris" },
      { name: "Yaris Cross" },
      { name: "Corolla" },
      { name: "Corolla Cross" },
      { name: "C-HR" },
      { name: "RAV4" },
      { name: "Camry" },
      { name: "Land Cruiser" },
      { name: "Land Cruiser Prado" },
      { name: "Highlander" },
      { name: "Hilux" },
      { name: "Proace" },
      { name: "Proace City" },
      { name: "bZ4X" },
      { name: "Supra" },
      { name: "Auris" },
      { name: "Avensis" },
      { name: "Verso" },
      { name: "Prius" },
    ],
  },
  {
    name: "Honda",
    models: [
      { name: "Jazz" },
      { name: "Civic" },
      { name: "Accord" },
      { name: "CR-V" },
      { name: "HR-V" },
      { name: "ZR-V" },
      { name: "e:Ny1" },
      { name: "City" },
    ],
  },
  {
    name: "Ford",
    models: [
      { name: "Fiesta" },
      { name: "Focus" },
      { name: "Mondeo" },
      { name: "Puma" },
      { name: "Kuga" },
      { name: "EcoSport" },
      { name: "Explorer" },
      { name: "Mustang" },
      { name: "Mustang Mach-E" },
      { name: "Ranger" },
      { name: "Transit" },
      { name: "Transit Custom" },
      { name: "Transit Connect" },
      { name: "Transit Courier" },
      { name: "Tourneo Connect" },
      { name: "Tourneo Custom" },
      { name: "Tourneo Courier" },
      { name: "F-150" },
      { name: "S-Max" },
      { name: "Galaxy" },
      { name: "C-Max" },
      { name: "B-Max" },
    ],
  },
  {
    name: "Renault",
    models: [
      { name: "Clio" },
      { name: "Megane" },
      { name: "Megane E-Tech" },
      { name: "Taliant" },
      { name: "Captur" },
      { name: "Kadjar" },
      { name: "Austral" },
      { name: "Koleos" },
      { name: "Espace" },
      { name: "Scenic" },
      { name: "Talisman" },
      { name: "Fluence" },
      { name: "Symbol" },
      { name: "Kangoo" },
      { name: "Trafic" },
      { name: "Master" },
      { name: "Zoe" },
      { name: "Arkana" },
      { name: "Twingo" },
      { name: "Laguna" },
    ],
  },
  {
    name: "Fiat",
    models: [
      { name: "Egea" },
      { name: "Egea Cross" },
      { name: "500" },
      { name: "500X" },
      { name: "500L" },
      { name: "500e" },
      { name: "Panda" },
      { name: "Tipo" },
      { name: "Doblo" },
      { name: "Fiorino" },
      { name: "Ducato" },
      { name: "Scudo" },
      { name: "Linea" },
      { name: "Punto" },
      { name: "Bravo" },
      { name: "Albea" },
      { name: "Palio" },
      { name: "Siena" },
      { name: "Fullback" },
    ],
  },
  {
    name: "Hyundai",
    models: [
      { name: "i10" },
      { name: "i20" },
      { name: "i30" },
      { name: "Elantra" },
      { name: "Bayon" },
      { name: "Kona" },
      { name: "Tucson" },
      { name: "Santa Fe" },
      { name: "Ioniq 5" },
      { name: "Ioniq 6" },
      { name: "Staria" },
      { name: "H-1" },
      { name: "Accent" },
      { name: "Accent Blue" },
      { name: "ix35" },
      { name: "Getz" },
    ],
  },
  {
    name: "Kia",
    models: [
      { name: "Picanto" },
      { name: "Rio" },
      { name: "Ceed" },
      { name: "Proceed" },
      { name: "Stonic" },
      { name: "Niro" },
      { name: "Sportage" },
      { name: "Sorento" },
      { name: "EV6" },
      { name: "EV9" },
      { name: "XCeed" },
      { name: "Soul" },
      { name: "Stinger" },
      { name: "Carnival" },
      { name: "Venga" },
      { name: "Optima" },
    ],
  },
  {
    name: "Opel",
    models: [
      { name: "Corsa" },
      { name: "Corsa-e" },
      { name: "Astra" },
      { name: "Astra-e" },
      { name: "Insignia" },
      { name: "Crossland" },
      { name: "Mokka" },
      { name: "Mokka-e" },
      { name: "Grandland" },
      { name: "Combo" },
      { name: "Combo Life" },
      { name: "Vivaro" },
      { name: "Movano" },
      { name: "Zafira" },
      { name: "Meriva" },
      { name: "Cascada" },
      { name: "Adam" },
      { name: "Karl" },
    ],
  },
  {
    name: "Peugeot",
    models: [
      { name: "208" },
      { name: "e-208" },
      { name: "308" },
      { name: "e-308" },
      { name: "408" },
      { name: "508" },
      { name: "2008" },
      { name: "e-2008" },
      { name: "3008" },
      { name: "5008" },
      { name: "Rifter" },
      { name: "Partner" },
      { name: "Expert" },
      { name: "Boxer" },
      { name: "301" },
      { name: "206" },
      { name: "207" },
      { name: "307" },
      { name: "407" },
      { name: "607" },
      { name: "RCZ" },
    ],
  },
  {
    name: "Citroen",
    models: [
      { name: "C1" },
      { name: "C3" },
      { name: "C3 Aircross" },
      { name: "C4" },
      { name: "C4 X" },
      { name: "e-C4" },
      { name: "C5 Aircross" },
      { name: "C5 X" },
      { name: "Berlingo" },
      { name: "Jumpy" },
      { name: "Jumper" },
      { name: "SpaceTourer" },
      { name: "DS3" },
      { name: "DS4" },
      { name: "DS5" },
      { name: "C-Elysee" },
      { name: "Cactus" },
      { name: "Nemo" },
    ],
  },
  {
    name: "Seat",
    models: [
      { name: "Ibiza" },
      { name: "Leon" },
      { name: "Arona" },
      { name: "Ateca" },
      { name: "Tarraco" },
      { name: "Toledo" },
      { name: "Alhambra" },
      { name: "Mii" },
      { name: "Altea" },
      { name: "Exeo" },
    ],
  },
  {
    name: "Skoda",
    models: [
      { name: "Fabia" },
      { name: "Scala" },
      { name: "Octavia" },
      { name: "Superb" },
      { name: "Kamiq" },
      { name: "Karoq" },
      { name: "Kodiaq" },
      { name: "Enyaq" },
      { name: "Rapid" },
      { name: "Roomster" },
      { name: "Yeti" },
    ],
  },
  {
    name: "Volvo",
    models: [
      { name: "S60" },
      { name: "S90" },
      { name: "V40" },
      { name: "V60" },
      { name: "V90" },
      { name: "XC40" },
      { name: "XC60" },
      { name: "XC90" },
      { name: "C40" },
      { name: "EX30" },
      { name: "EX90" },
      { name: "S40" },
      { name: "S80" },
    ],
  },
  {
    name: "Nissan",
    models: [
      { name: "Micra" },
      { name: "Juke" },
      { name: "Qashqai" },
      { name: "X-Trail" },
      { name: "Ariya" },
      { name: "Leaf" },
      { name: "Navara" },
      { name: "NV200" },
      { name: "NV300" },
      { name: "NV400" },
      { name: "Note" },
      { name: "Pulsar" },
      { name: "Murano" },
      { name: "Pathfinder" },
      { name: "370Z" },
      { name: "GT-R" },
    ],
  },
  {
    name: "Mazda",
    models: [
      { name: "2" },
      { name: "3" },
      { name: "6" },
      { name: "CX-3" },
      { name: "CX-30" },
      { name: "CX-5" },
      { name: "CX-60" },
      { name: "MX-5" },
      { name: "MX-30" },
      { name: "BT-50" },
    ],
  },
  {
    name: "Dacia",
    models: [
      { name: "Sandero" },
      { name: "Sandero Stepway" },
      { name: "Logan" },
      { name: "Logan MCV" },
      { name: "Duster" },
      { name: "Jogger" },
      { name: "Spring" },
      { name: "Dokker" },
      { name: "Lodgy" },
    ],
  },
  {
    name: "Alfa Romeo",
    models: [
      { name: "Giulia" },
      { name: "Stelvio" },
      { name: "Tonale" },
      { name: "Giulietta" },
      { name: "MiTo" },
      { name: "159" },
      { name: "Brera" },
      { name: "4C" },
    ],
  },
  {
    name: "Jeep",
    models: [
      { name: "Renegade" },
      { name: "Compass" },
      { name: "Cherokee" },
      { name: "Grand Cherokee" },
      { name: "Wrangler" },
      { name: "Gladiator" },
      { name: "Avenger" },
    ],
  },
  {
    name: "Land Rover",
    models: [
      { name: "Range Rover" },
      { name: "Range Rover Sport" },
      { name: "Range Rover Velar" },
      { name: "Range Rover Evoque" },
      { name: "Discovery" },
      { name: "Discovery Sport" },
      { name: "Defender" },
      { name: "Freelander" },
    ],
  },
  {
    name: "Jaguar",
    models: [
      { name: "XE" },
      { name: "XF" },
      { name: "F-Pace" },
      { name: "E-Pace" },
      { name: "I-Pace" },
      { name: "F-Type" },
      { name: "XJ" },
    ],
  },
  {
    name: "Porsche",
    models: [
      { name: "911" },
      { name: "718 Cayman" },
      { name: "718 Boxster" },
      { name: "Panamera" },
      { name: "Cayenne" },
      { name: "Macan" },
      { name: "Taycan" },
    ],
  },
  {
    name: "Mini",
    models: [
      { name: "Cooper" },
      { name: "Cooper S" },
      { name: "Clubman" },
      { name: "Countryman" },
      { name: "Cabrio" },
      { name: "John Cooper Works" },
      { name: "Electric" },
    ],
  },
  {
    name: "Lexus",
    models: [
      { name: "CT" },
      { name: "IS" },
      { name: "ES" },
      { name: "LS" },
      { name: "UX" },
      { name: "NX" },
      { name: "RX" },
      { name: "RZ" },
      { name: "LC" },
      { name: "LX" },
    ],
  },
  {
    name: "Infiniti",
    models: [
      { name: "Q30" },
      { name: "Q50" },
      { name: "Q60" },
      { name: "Q70" },
      { name: "QX30" },
      { name: "QX50" },
      { name: "QX60" },
      { name: "QX70" },
      { name: "QX80" },
    ],
  },
  {
    name: "Mitsubishi",
    models: [
      { name: "ASX" },
      { name: "Eclipse Cross" },
      { name: "Outlander" },
      { name: "L200" },
      { name: "Space Star" },
      { name: "Lancer" },
      { name: "Colt" },
      { name: "Pajero" },
    ],
  },
  {
    name: "Suzuki",
    models: [
      { name: "Swift" },
      { name: "Baleno" },
      { name: "Vitara" },
      { name: "S-Cross" },
      { name: "Jimny" },
      { name: "Ignis" },
      { name: "Across" },
      { name: "Swace" },
      { name: "SX4" },
      { name: "Grand Vitara" },
    ],
  },
  {
    name: "Subaru",
    models: [
      { name: "Impreza" },
      { name: "XV" },
      { name: "Forester" },
      { name: "Outback" },
      { name: "Legacy" },
      { name: "BRZ" },
      { name: "Levorg" },
      { name: "WRX" },
      { name: "Solterra" },
    ],
  },
  {
    name: "Tesla",
    models: [
      { name: "Model 3" },
      { name: "Model Y" },
      { name: "Model S" },
      { name: "Model X" },
      { name: "Cybertruck" },
    ],
  },
  {
    name: "Cupra",
    models: [
      { name: "Formentor" },
      { name: "Born" },
      { name: "Leon" },
      { name: "Ateca" },
      { name: "Tavascan" },
    ],
  },
  {
    name: "DS",
    models: [
      { name: "DS 3" },
      { name: "DS 3 Crossback" },
      { name: "DS 4" },
      { name: "DS 7" },
      { name: "DS 9" },
    ],
  },
  {
    name: "MG",
    models: [
      { name: "ZS" },
      { name: "ZS EV" },
      { name: "HS" },
      { name: "Marvel R" },
      { name: "MG4" },
      { name: "MG5" },
      { name: "Cyberster" },
    ],
  },
  {
    name: "BYD",
    models: [
      { name: "Atto 3" },
      { name: "Han" },
      { name: "Tang" },
      { name: "Seal" },
      { name: "Dolphin" },
      { name: "Seal U" },
    ],
  },
  {
    name: "Chery",
    models: [
      { name: "Tiggo 4 Pro" },
      { name: "Tiggo 7 Pro" },
      { name: "Tiggo 8 Pro" },
      { name: "Omoda 5" },
      { name: "Jaecoo 7" },
    ],
  },
  {
    name: "Togg",
    models: [
      { name: "T10X" },
      { name: "T10F" },
    ],
  },
  {
    name: "Chevrolet",
    models: [
      { name: "Aveo" },
      { name: "Cruze" },
      { name: "Spark" },
      { name: "Captiva" },
      { name: "Trax" },
      { name: "Camaro" },
      { name: "Corvette" },
    ],
  },
  {
    name: "Ssangyong",
    models: [
      { name: "Tivoli" },
      { name: "Korando" },
      { name: "Rexton" },
      { name: "Musso" },
      { name: "Torres" },
    ],
  },
  {
    name: "Isuzu",
    models: [
      { name: "D-Max" },
      { name: "MU-X" },
    ],
  },
  {
    name: "Maserati",
    models: [
      { name: "Ghibli" },
      { name: "Quattroporte" },
      { name: "Levante" },
      { name: "GranTurismo" },
      { name: "Grecale" },
      { name: "MC20" },
    ],
  },
  {
    name: "Ferrari",
    models: [
      { name: "Roma" },
      { name: "Portofino" },
      { name: "F8 Tributo" },
      { name: "SF90 Stradale" },
      { name: "296 GTB" },
      { name: "812 Superfast" },
      { name: "Purosangue" },
    ],
  },
  {
    name: "Lamborghini",
    models: [
      { name: "Huracan" },
      { name: "Urus" },
      { name: "Revuelto" },
    ],
  },
  {
    name: "Bentley",
    models: [
      { name: "Continental GT" },
      { name: "Flying Spur" },
      { name: "Bentayga" },
    ],
  },
  {
    name: "Rolls-Royce",
    models: [
      { name: "Ghost" },
      { name: "Phantom" },
      { name: "Wraith" },
      { name: "Dawn" },
      { name: "Cullinan" },
      { name: "Spectre" },
    ],
  },
  {
    name: "Aston Martin",
    models: [
      { name: "Vantage" },
      { name: "DB11" },
      { name: "DB12" },
      { name: "DBS" },
      { name: "DBX" },
    ],
  },
  {
    name: "McLaren",
    models: [
      { name: "720S" },
      { name: "750S" },
      { name: "Artura" },
      { name: "GT" },
    ],
  },
  {
    name: "Lotus",
    models: [
      { name: "Emira" },
      { name: "Eletre" },
      { name: "Evija" },
    ],
  },
  {
    name: "Polestar",
    models: [
      { name: "Polestar 2" },
      { name: "Polestar 3" },
      { name: "Polestar 4" },
    ],
  },
  {
    name: "Genesis",
    models: [
      { name: "G70" },
      { name: "G80" },
      { name: "G90" },
      { name: "GV60" },
      { name: "GV70" },
      { name: "GV80" },
    ],
  },
  {
    name: "Smart",
    models: [
      { name: "ForTwo" },
      { name: "ForFour" },
      { name: "#1" },
      { name: "#3" },
    ],
  },
  {
    name: "Lada",
    models: [
      { name: "Granta" },
      { name: "Vesta" },
      { name: "Niva" },
      { name: "XRay" },
    ],
  },
  {
    name: "Geely",
    models: [
      { name: "Coolray" },
      { name: "Atlas" },
      { name: "Tugella" },
      { name: "Monjaro" },
    ],
  },
].sort((a, b) => a.name.localeCompare(b.name, 'tr'));

export const BRAND_NAMES = VEHICLE_BRANDS.map(b => b.name);

export function getModelsByBrand(brandName: string): string[] {
  const brand = VEHICLE_BRANDS.find(b => b.name === brandName);
  return brand ? brand.models.map(m => m.name).sort((a, b) => a.localeCompare(b, 'tr')) : [];
}
